/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Coding;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Selling_Page extends javax.swing.JFrame {

    /**
     * Creates new form Selling_Page
     */
    public Selling_Page() {
        initComponents();
        
        /*
         Methods are called in the constructor because when the window will be opened 
         then these two method will execute first. 
        */
        ShowFlavourinCombobox();
        showFlavourinfoInTable();
      
    }

     DatabaseConnection db = new DatabaseConnection();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbflavourname = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tbxquantity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsellingtable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tbxtotalprice = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblcalculateprice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(77, 0, 77));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Flavour Name");

        cmbflavourname.setBackground(new java.awt.Color(230, 230, 230));
        cmbflavourname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity");

        tbxquantity.setBackground(new java.awt.Color(77, 0, 77));
        tbxquantity.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbxquantity.setForeground(new java.awt.Color(255, 255, 255));
        tbxquantity.setBorder(null);
        tbxquantity.setCaretColor(new java.awt.Color(255, 255, 255));
        tbxquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbxquantityKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbxquantityKeyTyped(evt);
            }
        });

        tblsellingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flavour Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblsellingtable);
        if (tblsellingtable.getColumnModel().getColumnCount() > 0) {
            tblsellingtable.getColumnModel().getColumn(0).setResizable(false);
            tblsellingtable.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Price");

        tbxtotalprice.setEditable(false);
        tbxtotalprice.setBackground(new java.awt.Color(77, 0, 77));
        tbxtotalprice.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbxtotalprice.setForeground(new java.awt.Color(255, 255, 255));
        tbxtotalprice.setBorder(null);
        tbxtotalprice.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("X");
        jLabel10.setToolTipText("Close");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("-");
        jLabel11.setToolTipText("Minimize");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("<");
        jLabel5.setToolTipText("Back");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        lblcalculateprice.setBackground(new java.awt.Color(77, 0, 77));
        lblcalculateprice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblcalculateprice.setForeground(new java.awt.Color(255, 255, 255));
        lblcalculateprice.setText("Calculate Price");
        lblcalculateprice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblcalculateprice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcalculateprice.setOpaque(true);
        lblcalculateprice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcalculatepriceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcalculatepriceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcalculatepriceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(cmbflavourname, 0, 196, Short.MAX_VALUE)
                    .addComponent(tbxquantity)
                    .addComponent(tbxtotalprice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcalculateprice)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbflavourname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcalculateprice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tbxtotalprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(518, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void tbxquantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxquantityKeyTyped
        // TODO add your handling code here:
        
        char number = evt.getKeyChar();           // consume all alphabetic input
        if(Character.isAlphabetic(number))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbxquantityKeyTyped

    private void CalculatePrice()
    {
        /* 
            select price from Product_table that admin entered.
            price will be calculated with the selected flavour. 
        */
        String flavour = cmbflavourname.getSelectedItem().toString();
        int quantity = Integer.parseInt(tbxquantity.getText());
        float bill =0;
        try
        {
           
            db.DbConnect();
            String sql = "Select price from Product_table where Flavour_name = ?";
            db.pstatement = db.con.prepareStatement(sql);
            db.pstatement.setString(1, flavour);
            db.rs = db.pstatement.executeQuery();
            if(db.rs.next())
            {
                int price = db.rs.getInt("price");          // calculating price for the selected combo item from the database
                bill = (price*quantity);
            }
            String Tprice = String.valueOf(bill);
            tbxtotalprice.setText(Tprice);

        } catch (NumberFormatException | SQLException e) 
        {
            System.out.print(e);
        }
        
        /*
        
            after calculating price of the selected flavour; quantity , flavour name, and total price will be
            saved in the database.

        */
          int confirm = JOptionPane.showConfirmDialog(null, "Do you want the selected item?", "Confirmation message", JOptionPane.YES_NO_OPTION);
        if(confirm == 0)
        {
        
        try 
        {
            String id = Stuff_login.StuffID;
            db.DbConnect();
            String Sql = "Insert into Selling_table (Flavour_name, Quantity, Bill) values (?,?,?)";
            db.pstatement = db.con.prepareStatement(Sql);
            
            db.pstatement.setString(1, flavour);
            db.pstatement.setInt(2, quantity);
            db.pstatement.setFloat(3, bill);
            
            db.pstatement.executeUpdate();
            tbxquantity.setText("");
            
        } catch (SQLException e) 
        {
            System.out.print(e);
            //JOptionPane.showMessageDialog(null, e);
        }
        }
        else
        {
            tbxquantity.setText("");
            tbxtotalprice.setText("");
        }
        
    }
    
    
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
        new Stuff_page().show();
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tbxquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxquantityKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            CalculatePrice();
        }
        
    }//GEN-LAST:event_tbxquantityKeyPressed

    private void lblcalculatepriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcalculatepriceMouseClicked
        // TODO add your handling code here:
        CalculatePrice();
    }//GEN-LAST:event_lblcalculatepriceMouseClicked

    private void lblcalculatepriceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcalculatepriceMouseEntered
        // TODO add your handling code here:
        lblcalculateprice.setBackground(new Color(255,255,255));
        lblcalculateprice.setForeground(new Color(77,0,77));
    }//GEN-LAST:event_lblcalculatepriceMouseEntered

    private void lblcalculatepriceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcalculatepriceMouseExited
        // TODO add your handling code here:
        lblcalculateprice.setBackground(new Color(77,0,77));
        lblcalculateprice.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblcalculatepriceMouseExited

    private void ShowFlavourinCombobox()
    {
        /*
        showing flavour name in the combo box from the database from Product_table 
        that admin inserted.
        */
        try 
        {   
            db.DbConnect();
            
            String sql = "Select Flavour_name from Product_table";
            db.pstatement = db.con.prepareStatement(sql);
            db.rs =  db.pstatement.executeQuery();
            
            while(db.rs.next())
            {
                String F_name = db.rs.getString("Flavour_name");
                cmbflavourname.addItem(F_name);
            }
            
        } catch (SQLException e) 
        {
            System.out.print(e);
        }
    }
    
    private void showFlavourinfoInTable()
    {
        
        /*
         adding flavour_name and price in the table
        */
        try 
        {
             db.DbConnect();
        
            String sql = "Select * from Product_table";
            db.pstatement = db.con.prepareStatement(sql);
            db.rs = db.pstatement.executeQuery();
            DefaultTableModel table = (DefaultTableModel) tblsellingtable.getModel();
            
            while(db.rs.next())
            {
                String F_name = db.rs.getString("Flavour_name");
                String F_price = db.rs.getString("price");
            
            table.addRow(new Object[]
            {
                F_name, F_price
            });
            }
        
        } catch (SQLException e) 
        {
            System.out.print(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selling_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selling_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selling_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selling_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Selling_Page().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbflavourname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblcalculateprice;
    private javax.swing.JTable tblsellingtable;
    private javax.swing.JTextField tbxquantity;
    private javax.swing.JTextField tbxtotalprice;
    // End of variables declaration//GEN-END:variables
}
